package com.starrail.sim.client;

import com.starrail.sim.StarRailSimMod;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import top.theillusivec4.curios.api.CuriosApi;

/** Client-side read-only access to the light cone equipped in the Curios slot. */
public final class StarRailLightConeClientData {
    private StarRailLightConeClientData() {
    }

    public static ItemStack findEquipped(Player player) {
        if (player == null) {
            return ItemStack.EMPTY;
        }
        ItemStack inTheNight = CuriosApi.getCuriosHelper()
                .findFirstCurio(player, StarRailSimMod.IN_THE_NIGHT.get())
                .map(result -> result.stack()).orElse(ItemStack.EMPTY);
        if (!inTheNight.isEmpty()) {
            return inTheNight;
        }
        return CuriosApi.getCuriosHelper()
                .findFirstCurio(player, StarRailSimMod.I_WILL_HUNT.get())
                .map(result -> result.stack())
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.WORRISOME_BLISSFUL.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.SLEEP_LIKE_THE_DEAD.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.PURE_THOUGHT_BAPTISM.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.IDEAL_BURNING_HELL.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.EMBARK_ON_SECOND_LIFE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.FINALE_OF_A_LIE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.SOMETHING_IRREPLACEABLE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.BRIGHTER_THAN_THE_SUN.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.DANCE_AT_SUNSET.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.THE_UNREACHABLE_SIDE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.THIS_BODY_AS_SWORD.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.NO_REWARD_CROWNING.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.BLOOD_FIRE_BURNING_PATH.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.WHERE_DREAMS_BELONG.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.DAWN_BURNS_JUST_SO.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.WHAT_YOU_SEE_IS_ME.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.GALAXY_RAILWAY.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.MOMENT_OF_GLORY.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.BEFORE_DAWN.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.PRICE_OF_PEACE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.TOWARDS_UNANSWERABLE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.NINJA_SCROLL.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.LIFE_AS_A_LIGHT.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.A_STAR_ILLUMINATES_NIGHT_SKY.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.SPARKLE_QUIETLY_SHINES.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.BATTLE_ISNT_OVER.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.MEMORY_OF_ME.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.NIGHT_FLOWING_COLORS.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.GAME_OF_COSMIC_WORLDS.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.RETURNING_TO_EARTH.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.IF_TIME_WERE_A_FLOWER.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.AN_AGE_ETCHED_IN_GOLDEN_BLOOD.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.IN_THE_NAME_OF_THE_WORLD.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.ON_THE_SHORE_IN_THE_FLOW_OF_TIME.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.A_THOUSAND_FOLD_SPRING.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.ONLY_WAIT.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.RAIN_NEVER_STOPS.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.LIES_IN_THE_WIND.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.RETURN_TO_LONG_ROAD.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.REFORGED_REMEMBRANCE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.OCEAN_WHY_SINGS.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.DO_NOT_FORGET_HER_FLAME.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.NEW_FLESH_OF_INFERNO.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.MOMENT_OF_VICTORY.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.SHE_HAS_CLOSED_HER_EYES.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.THOUGH_RIVERS_AND_MOUNTAINS.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.FATE_NEVER_FAIR.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.ECHOES_OF_THE_COFFIN.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.TIME_WAITS_FOR_NO_ONE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.NIGHT_OF_FRIGHT.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.ONLY_THE_SCENT_REMAINS.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.WEAVE_TIME_INTO_GOLD.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.MAKE_FAREWELL_MORE_BEAUTIFUL.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player, StarRailSimMod.LOVE_IS_ETERNAL.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.STARLIGHT_FOR_LONG_NIGHTS.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.WELCOME_TO_GALACTIC_CITY.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.MEET_IN_THE_NEXT_FLOWER_SEASON.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.WHEN_SHE_DECIDES_TO_SEE.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.FLOWER_WORLD_MESMERIZING_EYES.get())
                        .map(result -> result.stack()))
                .or(() -> CuriosApi.getCuriosHelper()
                        .findFirstCurio(player,
                                StarRailSimMod.MAY_RAINBOW_STAY_IN_THE_SKY.get())
                        .map(result -> result.stack()))
                .orElse(ItemStack.EMPTY);
    }
}
